### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by gitbygaurav** [AbdifatahYasin1/Todo-list#5]
Hi @AbdifatahYasin1 

Good job so far!
There are some issues that you still need to work on.

 ## (Highlights) Good Points: 💪 
 * Good commit messages. :heavy_check_mark:
 * No linter errors. :heavy_check_mark:
 * Followed Github flow :heavy_check_mark:
 * Professional README file. :heavy_check_mark:
 * All features are working properly :heavy_check_mark:
 
## Required Changes ♻️
 
*Please fix the alignment of your Input tasks field and your list items.
![peer to code review](https://user-images.githubusercontent.com/68365169/207250773-f2941722-745c-4336-895d-925661467069.png)

Cheers and Happy coding!👏👏👏

**Comment by AbdifatahYasin1** [comment]
thanks
